test2:
    resource: "@Test2Bundle/Resources/config/routing.yml"
    prefix:   /Test2

tests:
    resource: "@TestsBundle/Resources/config/routing.yml"
    prefix:   /Tests

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

